# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

symDiff <- function(v1, v2) {
    .Call('VineCopulaDAGCpp_symDiff', PACKAGE = 'VineCopulaDAGCpp', v1, v2)
}

setDiff <- function(v1, v2) {
    .Call('VineCopulaDAGCpp_setDiff', PACKAGE = 'VineCopulaDAGCpp', v1, v2)
}

processNodes <- function(j, nodes) {
    .Call('VineCopulaDAGCpp_processNodes', PACKAGE = 'VineCopulaDAGCpp', j, nodes)
}

finalizeMatrix <- function(x, i) {
    .Call('VineCopulaDAGCpp_finalizeMatrix', PACKAGE = 'VineCopulaDAGCpp', x, i)
}

finalizeMatrixOuter <- function(x, i) {
    .Call('VineCopulaDAGCpp_finalizeMatrixOuter', PACKAGE = 'VineCopulaDAGCpp', x, i)
}

